# appimage-builder recipe see https://appimage-builder.readthedocs.io for details
version: 1

script:
  - rm -rf ./AppDir || true
  - export DESTDIR=$PWD/AppDir
  - scripts/install-build-deps.sh
  - mkdir -p build
  - cd build
  - ../scripts/deploy-mauiman.sh
  - ../scripts/deploy-mauikit.sh
  - ../scripts/deploy-mauikit-filebrowsing.sh
  - ../scripts/install-maui-settings.sh
  - ../scripts/install-icon-theme.sh

AppDir:
  path: ./AppDir
  app_info:
    id: maui-settings
    name: maui-settings
    icon: nxmanager
    version: latest
    exec: usr/bin/MauiSettings
    exec_args: $@
  runtime:
    env:
      PATH: '${APPDIR}/usr/bin:${APPDIR}/bin:${APPDIR}/usr/lib/x86_64-linux-gnu/libexec/kf5:${PATH}'
      QT_QUICK_CONTROLS_STYLE: "maui-style"
  after_bundle:
    - cd $APPDIR/bin/ && ln -sf bash sh
  apt:
    arch:
    - amd64
    allow_unauthenticated: true
    sources:
    - sourceline: deb http://archive.ubuntu.com/ubuntu/ focal main restricted universe multiverse
    - sourceline: deb http://security.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse
    - sourceline: deb http://archive.ubuntu.com/ubuntu/ focal-updates main restricted universe multiverse
    - sourceline: deb http://archive.neon.kde.org/user focal main
      key_url: 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xE6D4736255751E5D'

    include:
    # CORE DEPENDENCIES
    - bash
    
    # QT QUICK DEPENDENCIES
    - qml-module-qtquick-controls2
    - qml-module-qtquick-shapes
    - qml-module-qtquick2
    - qml-module-qt-labs-settings
    - qml-module-qtquick-dialogs
    
    # KF5 DEPENDENCIES
    - libkf5notifications5
    - libkf5kiofilewidgets5

    # Other
    - libappimage1.0
    - qml-module-org-kde-kirigami2

    exclude:
    - "*dbgsym*"
    - "*-dev"
    - sound-theme-freedesktop
    - systemd
    - systemd-*
    - perl
    - perl-*
    - gnupg
    - libstdc++6

  files:
    include:
    - /usr/bin/which
    exclude:
    - usr/include
    - usr/share/man
    - usr/share/doc
    - usr/share/doc/*/README.*
    - usr/share/doc/*/changelog.*
    - usr/share/doc/*/NEWS.*
    - usr/share/doc/*/TODO.*
    - lib/systemd
    - etc/systemd
    - usr/bin/systemd*
    - usr/bin/dpkg*
    - usr/bin/*-linux-gnu-*
    - usr/share/locale

AppImage:
  arch: x86_64
  update-information: gh-releases-zsync|Nitrux|maui-settings|latest|*x86_64.AppImage.zsync