// This file was generated by ecm_setup_version(): DO NOT EDIT!

#ifndef MauiSettingsLib_VERSION_H
#define MauiSettingsLib_VERSION_H

#define MauiSettingsLib_VERSION_STRING "1.1.0"
#define MauiSettingsLib_VERSION_MAJOR 1
#define MauiSettingsLib_VERSION_MINOR 1
#define MauiSettingsLib_VERSION_PATCH 0
#define MauiSettingsLib_VERSION ((1<<16)|(1<<8)|(0))

#endif
