name: Maui Shell AppImage

on:
  push:
    branches: [ master ]

jobs:
  build-appimage:

    runs-on: ubuntu-22.04

    container:
      image: ubuntu:jammy
      env:
        DEBIAN_FRONTEND: noninteractive

    env:
          MAUIMAN_VERSION: v3.0.1
          BRANCH_MAUIKIT: v3.0.1
          BRANCH_MAUIKIT_FILEBROWSING: v3.0.1

    steps:
      - name: Install basic packages
        run: apt-get update -q && apt-get -qy install sudo && sudo apt-get -qy install curl wget gnupg python3-pip patchelf

      - name: Add required repo list
        run: |
          sudo touch /etc/apt/sources.list.d/neon.list
          echo "deb http://archive.neon.kde.org/user focal main" | sudo tee -a /etc/apt/sources.list.d/neon.list
          curl 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xE6D4736255751E5D' | sudo apt-key add -
          
          sudo apt-get update -q
      
      - name: Install appimagetool
        run: |
          wget -qc https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O /opt/appimagetool
          cd /opt/ && \
          chmod +x appimagetool && \
          sed -i 's|AI\x02|\x00\x00\x00|' appimagetool && \
          ./appimagetool --appimage-extract && \
          mv /opt/squashfs-root /opt/appimagetool.AppDir && \
          ln -s /opt/appimagetool.AppDir/AppRun /usr/local/bin/appimagetool && \
          rm /opt/appimagetool
          
      - name: Install AppImage Builder
        run: sudo pip3 install appimage-builder==0.9.2

      - uses: actions/checkout@v2
      - name: Build AppImage
        run: sudo -E appimage-builder --skip-tests --recipe maui-settings-appimage.yml

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "continuous"
          files: |
            ./*.AppImage*
